site_name: GFW Python Client
site_description: Thin Python wrapper for the Global Fishing Watch Gateway v3 API
site_author: Your Name
repo_url: https://github.com/your-org/your-repo
docs_dir: docs
nav:
  - Home: index.md
  - Quick-start: usage.md
  - API Reference: api_reference.md
  - Examples: examples.md
theme:
  name: material
  palette:
    scheme: default
markdown_extensions:
  - admonition
  - toc:
      permalink: true
