[project]
name = "ais-global-fishing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gfw-api-python-client>=1.0.1",
    "httpx>=0.28.1",
    "python-dotenv>=1.0.0",
]

